# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74a3fde08456efd256ceeead72475f28ef7df4969e40675715017b00cc68a3f97d7bd63d7eeec538e78d8dce3ca5b4d8e49893296cb09c193a9ccf22c27ad11d

test:
  secret_key_base: a1a57cdbdcf3be9f8b762021ded49b3f47426320c7d830383f383a31a4b176be2c8a328d0527e8afc6140433353f54ba90e42051319523b44764d2bf1f9ff8eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
